---
- name: Ensure memos folder exists
  ansible.builtin.file:
      path: "/etc/containers/systemd/memos"
      state: directory
      mode: "0755"

- name: Ensure memos service files are in place
  ansible.builtin.copy:
      src: "{{ item }}"
      dest: "/etc/containers/systemd/memos/{{ item }}"
      mode: "0644"
  loop:
      - memos.pod
      - memos.container
      - memos-data.volume
      - ts-memos.container
      - ts-memos-state.volume
      - memos.json
  notify: Reload Memos service

- name: Ensure memos service secrets are available
  containers.podman.podman_secret:
      state: present
      name: "ts-authkey"
      data: "{{ tailscale.ts_authkey }}"
  no_log: true
  notify: Reload Memos service

- name: Ensure memos service is started
  ansible.builtin.systemd_service:
      name: memos-pod.service
      state: started
