---
- name: Ensure Memos folder exists
  ansible.builtin.file:
      path: "/etc/containers/systemd/memos"
      state: directory

- name: Ensure Memos service files are in place
  ansible.builtin.copy:
      src: "memos/"
      dest: "/etc/containers/systemd/memos/"
  register: memos_files_changed
  notify: Restart Memos service

- name: Ensure Memos service secrets are available
  containers.podman.podman_secret:
      state: present
      name: "ts-authkey"
      data: "{{ tailscale.authkey }}"
  no_log: true
  register: memos_secrets_changed
  notify: Restart Memos service

- name: Ensure Memos service is running
  ansible.builtin.systemd_service:
      name: memos-pod.service
      state: started
      daemon_reload: true
  when: not (memos_files_changed.changed or memos_secrets_changed.changed)
