---
- name: Ensure memos folder exists
  ansible.builtin.file:
      path: "/etc/containers/systemd/memos"
      state: directory

- name: Ensure memos service files are in place
  ansible.builtin.copy:
      src: "memos/"
      dest: "/etc/containers/systemd/memos/"
  notify: Restart Memos service

- name: Ensure memos service secrets are available
  containers.podman.podman_secret:
      state: present
      name: "ts-authkey"
      data: "{{ tailscale.ts_authkey }}"
  no_log: true
  notify: Restart Memos service

- name: Ensure memos service is started
  ansible.builtin.systemd_service:
      name: memos-pod.service
      state: started
      daemon_reload: true
