---
- name: Ensure gitea folder exists
  ansible.builtin.file:
      path: "/etc/containers/systemd/gitea"
      state: directory
      mode: "0755"

- name: Ensure gitea service files are in place
  ansible.builtin.copy:
      src: "{{ item }}"
      dest: "/etc/containers/systemd/gitea/{{ item }}"
      mode: "0644"
  loop:
      - gitea.pod
      - gitea.container
      - gitea-data.volume
      - ts-gitea.container
      - ts-gitea-state.volume
      - gitea.json
  notify: Restart Gitea service
