services:
    tsidp:
        image: ghcr.io/lauritskarl/tsidp:v0.0.1
        container_name: tsidp
        environment:
            TS_AUTHKEY_FILE: /run/secrets/ts-authkey
            TAILSCALE_USE_WIP_CODE: 1
        secrets:
            - ts-authkey
        volumes:
            - tsidp-data:/var/lib/tsidp:Z
        command:
            - "tsidp"
            - "--hostname=idp"
            - "--dir=/var/lib/tsidp"
        restart: unless-stopped

secrets:
    ts-authkey:
        external: true

volumes:
    tsidp-data:
        name: tsidp-data
