---
- name: Ensure glance folder exists
  ansible.builtin.file:
      path: "/etc/containers/systemd/glance"
      state: directory
      mode: "0755"

- name: Ensure glance service files are in place
  ansible.builtin.copy:
      src: "{{ item }}"
      dest: "/etc/containers/systemd/glance/{{ item }}"
      mode: "0644"
  loop:
      - glance.pod
      - glance.container
      - ts-glance.container
      - ts-glance-state.volume
      - glance.json
  notify: Reload Glance service

- name: Ensure glance assets and config files are in place
  ansible.builtin.copy:
      src: "{{ item }}"
      dest: "/etc/containers/systemd/glance/"
      mode: "0755"
  loop:
      - assets
      - config
  notify: Reload Glance service

- name: Ensure glance service secrets are available
  containers.podman.podman_secret:
      state: present
      name: "ts-authkey"
      data: "{{ tailscale.ts_authkey }}"
  no_log: true
  notify: Reload Glance service

- name: Ensure glance service is started
  ansible.builtin.systemd_service:
      name: glance-pod.service
      state: started
