---
- name: Ensure glance folder exists
  ansible.builtin.file:
      path: "/etc/containers/systemd/glance"
      state: directory

- name: Ensure Glance service files are in place
  ansible.builtin.copy:
      src: "glance/"
      dest: "/etc/containers/systemd/glance/"
  register: glance_files_changed
  notify: Restart Glance service

- name: Ensure Glance service secrets are available
  containers.podman.podman_secret:
      state: present
      name: "ts-authkey"
      data: "{{ tailscale.ts_authkey }}"
  no_log: true
  register: glance_secrets_changed
  notify: Restart Glance service

- name: Ensure Glance service is running
  ansible.builtin.systemd_service:
      name: glance-pod.service
      state: started
      daemon_reload: true
  when: not (glance_files_changed.changed or glance_secrets_changed.changed)
