---
- name: Ensure glance folder exists
  ansible.builtin.file:
      path: "/etc/containers/systemd/glance"
      state: directory

- name: Ensure glance service files are in place
  ansible.builtin.copy:
      src: "glance/"
      dest: "/etc/containers/systemd/glance/"
  notify: Restart Glance service

- name: Ensure glance service secrets are available
  containers.podman.podman_secret:
      state: present
      name: "ts-authkey"
      data: "{{ tailscale.ts_authkey }}"
  no_log: true
  notify: Restart Glance service

- name: Ensure glance service is started
  ansible.builtin.systemd_service:
      name: glance-pod.service
      state: started
      daemon_reload: true
