---
- name: Ensure dumbdo folder exists
  ansible.builtin.file:
      path: "/etc/containers/systemd/dumbdo"
      state: directory

- name: Ensure Dumbdo service files are in place
  ansible.builtin.copy:
      src: "dumbdo/"
      dest: "/etc/containers/systemd/dumbdo/"
  register: dumbdo_files_changed
  notify: Restart Dumbdo service

- name: Ensure Dumbdo service secrets are available
  containers.podman.podman_secret:
      state: present
      name: "ts-authkey"
      data: "{{ tailscale.ts_authkey }}"
  no_log: true
  register: dumbdo_secrets_changed
  notify: Restart Dumbdo service

- name: Ensure Dumbdo service is running
  ansible.builtin.systemd_service:
      name: dumbdo-pod.service
      state: started
      daemon_reload: true
  when: not (dumbdo_files_changed.changed or dumbdo_secrets_changed.changed)
