services:
    traefik:
        image: traefik
        container_name: traefik
        volumes:
            - "$PWD/data/traefik/letsencrypt:/letsencrypt"
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
        ports:
            - 80:80
            - 443:443
        environment:
            - CF_DNS_API_TOKEN=$CF_DNS_API_TOKEN
        labels:
            - "traefik.enable=false"
        command:
            - --log.level=info
            - --accesslog=false
            - --api.insecure=true
            - --providers.docker=true
            - --providers.docker.exposedbydefault=false
            - --entrypoints.web.address=:80
            - --entrypoints.web.http.redirections.entryPoint.to=websecure
            - --entrypoints.web.http.redirections.entryPoint.scheme=https
            - --entrypoints.websecure.address=:443
            - --entrypoints.websecure.http.tls.certresolver=cloudflare
            - --certificatesresolvers.cloudflare.acme.dnschallenge=true
            - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
            - --certificatesresolvers.cloudflare.acme.email=karl@laurits.dev
            - --certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json
            - --serversTransport.insecureSkipVerify=true
        restart: unless-stopped
    pocketid:
        image: ghcr.io/pocket-id/pocket-id
        container_name: pocketid
        environment:
            - PUBLIC_APP_URL=https://id.laurits.dev
            - TRUST_PROXY=true
        volumes:
            - "$PWD/data/pocket-id/data:/app/backend/data"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.pocketid.rule=Host(`id.laurits.dev`)"
        healthcheck:
            test: "curl -f http://localhost/health"
            interval: 1m30s
            timeout: 5s
            retries: 2
            start_period: 10s
        restart: unless-stopped
    webfinger:
        image: nginx
        container_name: webfinger
        volumes:
            - "$PWD/data/webfinger:/usr/share/nginx/html:ro"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.webfinger.rule=Host(`laurits.dev`)"
        restart: unless-stopped
