services:
    pocket-id:
        image: ghcr.io/pocket-id/pocket-id:v1
        container_name: pocket-id
        networks:
            - proxy
        environment:
            - APP_URL=https://id.solisec.org
            - TRUST_PROXY=true
        volumes:
            - pocket-id-data:/app/data
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.pocketid.rule=Host(`id.solisec.org`)"
        healthcheck:
            test: ["CMD", "/app/pocket-id", "healthcheck"]
            interval: 1m30s
            timeout: 5s
            retries: 2
            start_period: 10s
        restart: unless-stopped

    webfinger:
        image: docker.io/nginx:latest
        container_name: webfinger
        networks:
            - proxy
        volumes:
            - ./webfinger:/usr/share/nginx/html/.well-known/webfinger:ro
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.webfinger.rule=Host(`solisec.org`)"
        restart: unless-stopped

networks:
    proxy:
        name: proxy
        external: true

volumes:
    pocket-id-data:
        name: pocket-id-data
        external: true
