#cloud-config
package_upgrade: true
packages:
    - firewalld
    - ansible
    - podman
    - podman-compose
    - podman-docker
    - podman-tui
    - cifs-utils
    - psmisc
    - net-tools
    - dnsutils
    - vim-default-editor
    - git
    - gh
users:
    - name: devops
      groups: wheel
      ssh-authorized-keys:
          - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMiYAIGJ3kMGsTYRl1Ho/pbrGf/GJAFwz9ULTSJAuO/S Karl's SSH Key"
    - name: ansible
      groups: wheel
      ssh-authorized-keys:
          - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMiYAIGJ3kMGsTYRl1Ho/pbrGf/GJAFwz9ULTSJAuO/S Karl's SSH Key"
write_files:
    - path: /etc/sudoers.d/wheel
      content: |
          %wheel ALL=(ALL) NOPASSWD:ALL
      owner: root
      group: root
      mode: 0440
cmd:
    - ["systemctl", "enable", "--now", "firewalld.service"]
    - ["systemctl", "enable", "--now", "podman.socket"]
    - ["systemctl", "enable", "--now", "podman-restart.service"]
    - ["systemctl", "enable", "--now", "podman-auto-update.timer"]
    - ["firewall-cmd", "--permanent", "--add-service=http"]
    - ["firewall-cmd", "--permanent", "--add-service=https"]
    - ["firewall-cmd", "--reload"]
    - ["curl", "-fsSL", "https://tailscale.com/install.sh", "|", "sh"]
