#cloud-config
package_upgrade: true
packages:
    - firewalld
users:
    - name: ansible
      groups: wheel
    - name: devops
      groups: wheel
write_files:
    - path: /etc/sudoers.d/wheel
      content: |
          %wheel ALL=(ALL) NOPASSWD:ALL
      owner: root
      group: root
      mode: 0440
runcmd:
    - ["systemctl", "enable", "--now", "firewalld.service"]
    - ["sh", "-c", "curl -fsSL https://tailscale.com/install.sh | sh"]
    - ["tailscale", "up", "--auth-key=TAILSCALE_AUTH_KEY"]
    - ["tailscale", "set", "--ssh"]
