#cloud-config
package_upgrade: true
users:
    - name: devops
      groups: wheel
      shell: /bin/bash
      sudo: ALL=(ALL) NOPASSWD:ALL
      ssh-authorized-keys:
          - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMiYAIGJ3kMGsTYRl1Ho/pbrGf/GJAFwz9ULTSJAuO/S Karl's SSH Key"
    - name: ansible
      groups: wheel
      shell: /bin/bash
      sudo: ALL=(ALL) NOPASSWD:ALL
      ssh-authorized-keys:
          - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMiYAIGJ3kMGsTYRl1Ho/pbrGf/GJAFwz9ULTSJAuO/S Karl's SSH Key"
packages:
    - firewalld
    - vim-default-editor
    - git
    - gh
    - cifs-utils
    - psmisc
    - net-tools
    - dnsutils
cmd:
    - ["systemctl", "enable", "--now", "firewalld"]
    - ["firewall-cmd", "--permanent", "--add-service=http"]
    - ["firewall-cmd", "--permanent", "--add-service=https"]
    - ["firewall-cmd", "--reload"]
    - [
          "curl",
          "-fsSL",
          "https://get.docker.com",
          "-o",
          "get-docker.sh",
          "&&",
          "sh",
          "get-docker.sh",
      ]
    - ["curl", "-fsSL", "https://tailscale.com/install.sh", "|", "sh"]
