services:
    ts-bitwarden:
        image: docker.io/tailscale/tailscale:latest
        container_name: ts-bitwarden
        hostname: bitwarden
        environment:
            - TS_AUTHKEY=$TS_AUTHKEY
            - TS_STATE_DIR=/var/lib/tailscale
            - TS_USERSPACE=false
            - TS_SERVE_CONFIG=/config/serve-config.json
        volumes:
            - ./data/ts-bitwarden/state:/var/lib/tailscale
            - ./data/ts-bitwarden/config:/config
        devices:
            - /dev/net/tun:/dev/net/tun
        cap_add:
            - net_admin
        restart: unless-stopped
    bitwarden:
        image: ghcr.io/bitwarden/self-host:beta
        container_name: bitwarden
        network_mode: service:ts-bitwarden
        depends_on:
            - ts-bitwarden
        env_file:
            - .env
        volumes:
            - ./data/bitwarden:/etc/bitwarden
        restart: unless-stopped
