---
- name: Ensure dumbbudget folder exists
  ansible.builtin.file:
      path: "/etc/containers/systemd/dumbbudget"
      state: directory
      mode: "0755"

- name: Ensure dumbbudget service files are in place
  ansible.builtin.copy:
      src: "{{ item }}"
      dest: "/etc/containers/systemd/dumbbudget/{{ item }}"
      mode: "0644"
  loop:
      - dumbbudget.pod
      - dumbbudget.container
      - dumbbudget-data.volume
      - ts-dumbbudget.container
      - ts-dumbbudget-state.volume
      - dumbbudget.json
  notify: Restart Dumbbudget service

- name: Ensure dumbbudget service secrets are available
  containers.podman.podman_secret:
      state: present
      name: "ts-authkey"
      data: "{{ tailscale.ts_authkey }}"
  no_log: true
  notify: Restart Dumbbudget service
