---
- name: Ensure Dumbbudget folder exists
  ansible.builtin.file:
      path: "/etc/containers/systemd/dumbbudget"
      state: directory

- name: Ensure Dumbbudget service files are in place
  ansible.builtin.copy:
      src: "dumbbudget/"
      dest: "/etc/containers/systemd/dumbbudget/"
  register: dumbbudget_files_changed
  notify: Restart Dumbbudget service

- name: Ensure Dumbbudget service secrets are available
  containers.podman.podman_secret:
      state: present
      name: "ts-authkey"
      data: "{{ tailscale.ts_authkey }}"
  no_log: true
  register: dumbbudget_secrets_changed
  notify: Restart Dumbbudget service

- name: Ensure Dumbbudget service is running
  ansible.builtin.systemd_service:
      name: dumbbudget-pod.service
      state: started
      daemon_reload: true
  when: not (dumbbudget_files_changed.changed or dumbbudget_secrets_changed.changed)
