---
- name: Ensure dumbkan folder exists
  ansible.builtin.file:
      path: "/etc/containers/systemd/dumbkan"
      state: directory

- name: Ensure dumbkan service files are in place
  ansible.builtin.copy:
      src: "dumbkan/"
      dest: "/etc/containers/systemd/dumbkan/"
  register: dumbkan_files_changed
  notify: Restart Dumbkan service

- name: Ensure dumbkan service secrets are available
  containers.podman.podman_secret:
      state: present
      name: "ts-authkey"
      data: "{{ tailscale.ts_authkey }}"
  no_log: true
  register: dumbkan_secrets_changed
  notify: Restart Dumbkan service

- name: Ensure dumbkan service is running
  ansible.builtin.systemd_service:
      name: dumbkan-pod.service
      state: started
      daemon_reload: true
  when: not (dumbkan_files_changed.changed or dumbkan_secrets_changed.changed)
