---
- name: Ensure dumbkan folder exists
  ansible.builtin.file:
      path: "/etc/containers/systemd/dumbkan"
      state: directory
      mode: "0755"

- name: Ensure dumbkan service files are in place
  ansible.builtin.copy:
      src: "{{ item }}"
      dest: "/etc/containers/systemd/dumbkan/{{ item }}"
      mode: "0644"
  loop:
      - dumbkan.pod
      - dumbkan.container
      - dumbkan-data.volume
      - ts-dumbkan.container
      - ts-dumbkan-state.volume
      - dumbkan.json
  notify: Restart Dumbkan service

- name: Ensure dumbkan service secrets are available
  containers.podman.podman_secret:
      state: present
      name: "ts-authkey"
      data: "{{ tailscale.ts_authkey }}"
  no_log: true
  notify: Restart Dumbkan service

- name: Ensure dumbkan service is started
  ansible.builtin.systemd_service:
      name: dumbkan-pod.service
      state: started
