---
- name: Ensure jellyfin folder exists
  ansible.builtin.file:
      path: "/etc/containers/systemd/jellyfin"
      state: directory

- name: Ensure jellyfin service files are in place
  ansible.builtin.copy:
      src: "jellyfin/"
      dest: "/etc/containers/systemd/jellyfin/"
  notify: Restart Jellyfin service

- name: Ensure jellyfin service secrets are available
  containers.podman.podman_secret:
      state: present
      name: "ts-authkey"
      data: "{{ tailscale.ts_authkey }}"
  no_log: true
  notify: Restart Jellyfin service

- name: Ensure jellyfin service is started
  ansible.builtin.systemd_service:
      name: jellyfin-pod.service
      state: started
      daemon_reload: true
