---
- name: Ensure jellyfin folder exists
  ansible.builtin.file:
      path: "/etc/containers/systemd/jellyfin"
      state: directory

- name: Ensure Jellyfin service files are in place
  ansible.builtin.copy:
      src: "jellyfin/"
      dest: "/etc/containers/systemd/jellyfin/"
  register: jellyfin_files_changed
  notify: Restart Jellyfin service

- name: Ensure Jellyfin service secrets are available
  containers.podman.podman_secret:
      state: present
      name: "ts-authkey"
      data: "{{ tailscale.ts_authkey }}"
  no_log: true
  register: jellyfin_secrets_changed
  notify: Restart Jellyfin service

- name: Ensure Jellyfin service is running
  ansible.builtin.systemd_service:
      name: jellyfin-pod.service
      state: started
      daemon_reload: true
  when: not (jellyfin_files_changed.changed or jellyfin_secrets_changed.changed)
