services:
    traefik:
        image: traefik:v3
        container_name: traefik
        networks:
            - proxy
        volumes:
            - ./data/traefik/config:/etc/traefik
            - ./data/traefik/letsencrypt:/letsencrypt
            - /var/run/docker.sock:/var/run/docker.sock:ro
        ports:
            - "80:80"
            - "443:443"
        environment:
            - CF_DNS_API_TOKEN=$CF_DNS_API_TOKEN
        labels:
            - "traefik.enable=false"
        restart: unless-stopped
networks:
    proxy:
        name: proxy
