global:
    checkNewVersion: true
    sendAnonymousUsage: false

log:
    level: INFO

api:
    insecure: true
    dashboard: false

providers:
    docker:
        exposedByDefault: false

certificatesResolvers:
    letsencrypt:
        acme:
            dnsChallenge:
                provider: cloudflare
            email: postmaster@solisec.org
            storage: /letsencrypt/acme.json

entryPoints:
    http:
        address: ":80"
        http3: {}
        http:
            redirections:
                entryPoint:
                    to: https
                    scheme: https

    https:
        address: ":443"
        http3: {}
        http:
            tls:
                certResolver: letsencrypt

tls:
    options:
        default:
            minVersion: VersionTLS12

serversTransport:
    insecureSkipVerify: true
