---
- name: Ensure SearXNG folder exists
  ansible.builtin.file:
      path: "/etc/containers/systemd/searxng"
      state: directory

- name: Ensure SearXNG service files are in place
  ansible.builtin.copy:
      src: "searxng/"
      dest: "/etc/containers/systemd/searxng/"
  register: searxng_files_changed
  notify: Restart SearXNG service

- name: Ensure SearXNG service secrets are available
  containers.podman.podman_secret:
      state: present
      name: "ts-authkey"
      data: "{{ tailscale.authkey }}"
  no_log: true
  register: searxng_secrets_changed
  notify: Restart SearXNG service

- name: Ensure SearXNG service is running
  ansible.builtin.systemd_service:
      name: searxng-pod.service
      state: started
      daemon_reload: true
  when: not (searxng_files_changed.changed or searxng_secrets_changed.changed)
