---
- name: Ensure searxng folder exists
  ansible.builtin.file:
      path: "/etc/containers/systemd/searxng"
      state: directory

- name: Ensure searxng service files are in place
  ansible.builtin.copy:
      src: "searxng/"
      dest: "/etc/containers/systemd/searxng/"
  notify: Restart Searxng service

- name: Ensure searxng service secrets are available
  containers.podman.podman_secret:
      state: present
      name: "ts-authkey"
      data: "{{ tailscale.ts_authkey }}"
  no_log: true
  notify: Restart Searxng service

- name: Ensure searxng service is started
  ansible.builtin.systemd_service:
      name: searxng-pod.service
      state: started
      daemon_reload: true
