---
- name: Ensure tsidp folder exists
  ansible.builtin.file:
      path: "/etc/containers/systemd/tsidp"
      state: directory
      mode: "0755"

- name: Ensure tsidp service files are in place
  ansible.builtin.copy:
      src: "{{ item }}"
      dest: "/etc/containers/systemd/tsidp/{{ item }}"
      mode: "0644"
  loop:
      - tsidp.container
      - tsidp-data.volume
  notify: Restart Tsidp service

- name: Ensure tsidp service secrets are available
  containers.podman.podman_secret:
      state: present
      name: "ts-authkey"
      data: "{{ tailscale.ts_authkey }}"
  no_log: true
  notify: Restart Tsidp service

- name: Ensure tsidp service is started
  ansible.builtin.systemd_service:
      name: tsidp-pod.service
      state: started
