---
- name: Ensure tsidp folder exists
  ansible.builtin.file:
      path: "/etc/containers/systemd/tsidp"
      state: directory

- name: Ensure tsidp service files are in place
  ansible.builtin.copy:
      src: "tsidp/"
      dest: "/etc/containers/systemd/tsidp/"
  register: tsidp_files_changed
  notify: Restart tsidp service

- name: Ensure tsidp service secrets are available
  containers.podman.podman_secret:
      state: present
      name: "ts-authkey"
      data: "{{ tailscale.ts_authkey }}"
  no_log: true
  register: tsidp_secrets_changed
  notify: Restart tsidp service

- name: Ensure tsidp service is running
  ansible.builtin.systemd_service:
      name: tsidp-pod.service
      state: started
      daemon_reload: true
  when: not (tsidp_files_changed.changed or tsidp_secrets_changed.changed)
