---
- name: Ensure tsidp folder exists
  ansible.builtin.file:
      path: "/etc/containers/systemd/tsidp"
      state: directory

- name: Ensure tsidp service files are in place
  ansible.builtin.copy:
      src: "tsidp/"
      dest: "/etc/containers/systemd/tsidp/"
  notify: Restart Tsidp service

- name: Ensure tsidp service secrets are available
  containers.podman.podman_secret:
      state: present
      name: "ts-authkey"
      data: "{{ tailscale.ts_authkey }}"
  no_log: true
  notify: Restart Tsidp service

- name: Ensure tsidp service is started
  ansible.builtin.systemd_service:
      name: tsidp-pod.service
      state: started
      daemon_reload: true
