services:
    ts-rss:
        image: tailscale/tailscale:latest
        container_name: ts-rss
        hostname: rss
        environment:
            - TS_AUTHKEY=$TS_AUTHKEY
            - TS_STATE_DIR=/var/lib/tailscale
            - TS_USERSPACE=false
            - TS_SERVE_CONFIG=/config/serve-config.json
        volumes:
            - $PWD/data/ts-rss/state:/var/lib/tailscale
            - $PWD/data/ts-rss/config:/config
        devices:
            - /dev/net/tun:/dev/net/tun
        cap_add:
            - net_admin
        restart: unless-stopped
    rss:
        image: codeberg.org/danb/rss:latest
        container_name: rss
        network_mode: service:ts-rss
        depends_on:
            - ts-rss
        environment:
            - APP_NAME=RSS
            - APP_CONFIG_FILE=/app/storage/feeds.txt
            - APP_LOAD_POST_THUMBNAILS=true
            - APP_FEED_UPDATE_FREQUENCY=60
            - APP_PRUNE_POSTS_AFTER_DAYS=30
        volumes:
            - $PWD/data/rss:/app/storage
        restart: unless-stopped
