services:
    ts-dumbkan:
        image: docker.io/tailscale/tailscale:latest
        container_name: ts-dumbkan
        hostname: dumbkan
        environment:
            - TS_AUTHKEY=$TS_AUTHKEY
            - TS_STATE_DIR=/var/lib/tailscale
            - TS_USERSPACE=false
            - TS_SERVE_CONFIG=/config/serve-config.json
        volumes:
            - ts-dumbkan-state:/var/lib/tailscale
            - ./serve-config.json:/config/serve-config.json
        devices:
            - /dev/net/tun:/dev/net/tun
        cap_add:
            - net_admin
        restart: unless-stopped
    dumbkan:
        image: docker.io/dumbwareio/dumbkan:latest
        container_name: dumbkan
        network_mode: service:ts-dumbkan
        depends_on:
            - ts-dumbkan
        volumes:
            - dumbkan-data:/app/data
        restart: unless-stopped

volumes:
    ts-dumbkan-state:
        name: ts-dumbkan-state
    dumbkan-data:
        name: dumbkan-data
