---
- name: Ensure dumbpad folder exists
  ansible.builtin.file:
      path: "/etc/containers/systemd/dumbpad"
      state: directory
      mode: "0755"

- name: Ensure dumbpad service files are in place
  ansible.builtin.copy:
      src: "{{ item }}"
      dest: "/etc/containers/systemd/dumbpad/{{ item }}"
      mode: "0644"
  loop:
      - dumbpad.pod
      - dumbpad.container
      - dumbpad-data.volume
      - ts-dumbpad.container
      - ts-dumbpad-state.volume
      - dumbpad.json
  notify: Restart Dumbpad service

- name: Ensure dumbpad service secrets are available
  containers.podman.podman_secret:
      state: present
      name: "ts-authkey"
      data: "{{ tailscale.ts_authkey }}"
  no_log: true
  notify: Restart Dumbpad service

- name: Ensure dumbpad service is started
  ansible.builtin.systemd_service:
      name: dumbpad-pod.service
      state: started
