---
- name: Ensure dumbpad folder exists
  ansible.builtin.file:
      path: "/etc/containers/systemd/dumbpad"
      state: directory

- name: Ensure dumbpad service files are in place
  ansible.builtin.copy:
      src: "dumbpad/"
      dest: "/etc/containers/systemd/dumbpad/"
  notify: Restart Dumbpad service

- name: Ensure dumbpad service secrets are available
  containers.podman.podman_secret:
      state: present
      name: "ts-authkey"
      data: "{{ tailscale.ts_authkey }}"
  no_log: true
  notify: Restart Dumbpad service

- name: Ensure dumbpad service is started
  ansible.builtin.systemd_service:
      name: dumbpad-pod.service
      state: started
      daemon_reload: true
