services:
    ts-dumbdo:
        image: docker.io/tailscale/tailscale:latest
        container_name: ts-dumbdo
        hostname: dumbdo
        environment:
            - TS_AUTHKEY=$TS_AUTHKEY
            - TS_STATE_DIR=/var/lib/tailscale
            - TS_USERSPACE=false
            - TS_SERVE_CONFIG=/config/serve-config.json
        volumes:
            - ts-dumbdo-state:/var/lib/tailscale
            - ./serve-config.json:/config/serve-config.json
        devices:
            - /dev/net/tun:/dev/net/tun
        cap_add:
            - net_admin
        restart: unless-stopped

    dumbdo:
        image: docker.io/dumbwareio/dumbdo:latest
        container_name: dumbdo
        network_mode: service:ts-dumbdo
        depends_on:
            - ts-dumbdo
        volumes:
            - dumbdo-data:/app/data
        restart: unless-stopped

volumes:
    ts-dumbdo-state:
        name: ts-dumbdo-state
    dumbdo-data:
        name: dumbdo-data
