services:
    ts-dumbassets:
        image: docker.io/tailscale/tailscale:latest
        container_name: ts-dumbassets
        hostname: dumbassets
        environment:
            TS_AUTHKEY_FILE: /run/secrets/ts-authkey
            TS_STATE_DIR: /var/lib/tailscale
            TS_USERSPACE: false
            TS_SERVE_CONFIG: /config/serve-config.json
        secrets:
            - ts-authkey
        volumes:
            - ts-dumbassets-state:/var/lib/tailscale
            - ./serve-config.json:/config/serve-config.json
        devices:
            - /dev/net/tun:/dev/net/tun
        cap_add:
            - net_admin
        restart: unless-stopped

    dumbassets:
        image: docker.io/dumbwareio/dumbassets:latest
        container_name: dumbassets
        network_mode: service:ts-dumbassets
        depends_on:
            - ts-dumbassets
        environment:
            TZ: Europe/Tallinn
        volumes:
            - dumbassets-data:/app/data
        restart: unless-stopped

secrets:
    ts-authkey:
        external: true

volumes:
    ts-dumbassets-state:
        name: ts-dumbassets-state
    dumbassets-data:
        name: dumbassets-data
