services:
    ts-dumbassets:
        image: tailscale/tailscale:latest
        container_name: ts-dumbassets
        hostname: dumbassets
        environment:
            - TS_AUTHKEY=$TS_AUTHKEY
            - TS_STATE_DIR=/var/lib/tailscale
            - TS_USERSPACE=false
            - TS_SERVE_CONFIG=/config/serve-config.json
        volumes:
            - $PWD/data/ts-dumbassets/state:/var/lib/tailscale
            - $PWD/data/ts-dumbassets/config:/config
        devices:
            - /dev/net/tun:/dev/net/tun
        cap_add:
            - net_admin
        restart: unless-stopped
    dumbassets:
        image: dumbwareio/dumbassets:latest
        container_name: dumbassets
        network_mode: service:ts-dumbassets
        depends_on:
            - ts-dumbassets
        environment:
            - BASE_URL=https://dumbassets.duckbill-karat.ts.net
        volumes:
            - "$PWD/data/dumbassets:/app/data"
        restart: unless-stopped
