---
- name: Ensure bitwarden folder exists
  ansible.builtin.file:
      path: "/etc/containers/systemd/bitwarden"
      state: directory
      mode: "0755"

- name: Ensure bitwarden service files are in place
  ansible.builtin.copy:
      src: "{{ item }}"
      dest: "/etc/containers/systemd/bitwarden/{{ item }}"
      mode: "0644"
  loop:
      - bitwarden.pod
      - bitwarden.container
      - bitwarden-data.volume
      - ts-bitwarden.container
      - ts-bitwarden-state.volume
      - bitwarden.json
  notify: Restart Bitwarden service

- name: Ensure bitwarden service secrets are available
  containers.podman.podman_secret:
      state: present
      name: "{{ item.name }}"
      data: "{{ item.data }}"
  loop:
      - name: ts-authkey
        data: "{{ tailscale.ts_authkey }}"
      - name: bw-domain
        data: "{{ bitwarden.bw_domain }}"
      - name: bw-installation-id
        data: "{{ bitwarden.bw_installation_id }}"
      - name: bw-installation-key
        data: "{{ bitwarden.bw_installation_key }}"
      - name: bw-admins
        data: "{{ bitwarden.bw_admins }}"
  no_log: true
  notify: Restart Bitwarden service

- name: Ensure bitwarden service is started
  ansible.builtin.systemd_service:
      name: bitwarden-pod.service
      state: started
