---
- name: Ensure pocket-id folder exists
  ansible.builtin.file:
      path: "/etc/containers/systemd/pocket-id"
      state: directory

- name: Ensure pocket-id service files are in place
  ansible.builtin.copy:
      src: "pocket-id/"
      dest: "/etc/containers/systemd/pocket-id/"
  notify: Restart Pocket ID service

- name: Ensure pocket-id service secrets are available
  containers.podman.podman_secret:
      state: present
      name: "cf-tunnel-token"
      data: "{{ cloudflare.cf_tunnel_token }}"
  no_log: true
  notify: Restart Pocket ID service

- name: Ensure pocket-id service is started
  ansible.builtin.systemd_service:
      name: pocket-id-pod.service
      state: started
      daemon_reload: true
