---
- name: Ensure immich folder exists
  ansible.builtin.file:
      path: "/etc/containers/systemd/immich"
      state: directory

- name: Ensure Immich service files are in place
  ansible.builtin.copy:
      src: "immich/"
      dest: "/etc/containers/systemd/immich/"
  register: immich_files_changed
  notify: Restart Immich service

- name: Ensure Immich service secrets are available
  containers.podman.podman_secret:
      state: present
      name: "{{ item.name }}"
      data: "{{ item.data }}"
  loop:
      - name: ts-authkey
        data: "{{ tailscale.ts_authkey }}"
      - name: immich-db-password
        data: "{{ immich.db_password }}"
      - name: immich-db-username
        data: "{{ immich.db_username }}"
      - name: immich-db-name
        data: "{{ immich.db_name }}"
  register: immich_secrets_changed
  no_log: true
  notify: Restart Immich service

- name: Ensure Immich service is running
  ansible.builtin.systemd_service:
      name: immich-pod.service
      state: started
      daemon_reload: true
  when: not (immich_files_changed.changed or immich_secrets_changed.changed)
