---
- name: Ensure immich folder exists
  ansible.builtin.file:
      path: "/etc/containers/systemd/immich"
      state: directory
      mode: "0755"

- name: Ensure Immich service files are in place
  ansible.builtin.copy:
      src: "{{ item }}"
      dest: "/etc/containers/systemd/immich/{{ item }}"
      mode: "0644"
  loop:
      - immich.pod
      - immich-server.container
      - immich-postgres.container
      - immich-postgres.volume
      - immich-machine-learning.container
      - immich-model-cache.volume
      - immich-redis.container
      - ts-immich.container
      - ts-immich-state.volume
      - immich.json
  notify: Restart Immich service

- name: Ensure Immich service secrets are available
  containers.podman.podman_secret:
      state: present
      name: "{{ item.name }}"
      data: "{{ item.data }}"
  loop:
      - name: ts-authkey
        data: "{{ tailscale.ts_authkey }}"
      - name: immich-db-password
        data: "{{ immich.db_password }}"
      - name: immich-db-username
        data: "{{ immich.db_username }}"
      - name: immich-db-name
        data: "{{ immich.db_name }}"
  no_log: true
  notify: Restart Immich service

- name: Ensure Immich service is started
  ansible.builtin.systemd_service:
      name: immich-pod.service
      state: started
