services:
    ts-jellyfin:
        image: docker.io/tailscale/tailscale:latest
        container_name: ts-jellyfin
        hostname: jellyfin
        environment:
            TS_AUTHKEY_FILE: /run/secrets/ts-authkey
            TS_STATE_DIR: /var/lib/tailscale
            TS_USERSPACE: false
            TS_SERVE_CONFIG: /config/serve-config.json
        secrets:
            - ts-authkey
        volumes:
            - ts-jellyfin-state:/var/lib/tailscale:Z
            - ./serve-config.json:/config/serve-config.json:Z,ro
        devices:
            - /dev/net/tun:/dev/net/tun
        cap_add:
            - net_admin
        restart: unless-stopped

    jellyfin:
        image: docker.io/jellyfin/jellyfin:latest
        container_name: jellyfin
        network_mode: service:ts-jellyfin
        depends_on:
            - ts-jellyfin
        volumes:
            - jellyfin-config:/config:Z
            - jellyfin-cache:/cache:Z
            - type: bind
              source: /mnt/nas/MEDIA
              target: /media
              read_only: true
        restart: unless-stopped

secrets:
    ts-authkey:
        external: true

volumes:
    ts-jellyfin-state:
        name: ts-jellyfin-state
    jellyfin-config:
        name: jellyfin-config
    jellyfin-cache:
        name: jellyfin-cache
