---
- name: Ensure Dumbassets folder exists
  ansible.builtin.file:
      path: "/etc/containers/systemd/dumbassets"
      state: directory

- name: Ensure Dumbassets service files are in place
  ansible.builtin.copy:
      src: "dumbassets/"
      dest: "/etc/containers/systemd/dumbassets/"
  register: dumbassets_files_changed
  notify: Restart Dumbassets service

- name: Ensure Dumbassets service secrets are available
  containers.podman.podman_secret:
      state: present
      name: "ts-authkey"
      data: "{{ tailscale.ts_authkey }}"
  no_log: true
  register: dumbassets_secrets_changed
  notify: Restart Dumbassets service

- name: Ensure Dumbassets service is running
  ansible.builtin.systemd_service:
      name: dumbassets-pod.service
      state: started
      daemon_reload: true
  when: not (dumbassets_files_changed.changed or dumbassets_secrets_changed.changed)
