---
- name: Ensure dumbassets folder exists
  ansible.builtin.file:
      path: "/etc/containers/systemd/dumbassets"
      state: directory
      mode: "0755"

- name: Ensure dumbassets service files are in place
  ansible.builtin.copy:
      src: "{{ item }}"
      dest: "/etc/containers/systemd/dumbassets/{{ item }}"
      mode: "0644"
  loop:
      - dumbassets.pod
      - dumbassets.container
      - dumbassets-data.volume
      - ts-dumbassets.container
      - ts-dumbassets-state.volume
      - dumbassets.json
  notify: Reload Dumbassets service

- name: Ensure dumbassets service secrets are available
  containers.podman.podman_secret:
      state: present
      name: "ts-authkey"
      data: "{{ tailscale.ts_authkey }}"
  no_log: true
  notify: Reload Dumbassets service

- name: Ensure dumbassets service is started
  ansible.builtin.systemd_service:
      name: dumbassets-pod.service
      state: started
