services:
    ts-bitwarden:
        image: ghcr.io/tailscale/tailscale:latest
        container_name: ts-bitwarden
        hostname: bitwarden
        environment:
            TS_AUTHKEY_FILE: /run/secrets/ts-authkey
            TS_STATE_DIR: /var/lib/tailscale
            TS_USERSPACE: false
            TS_SERVE_CONFIG: /config/bitwarden.json
        secrets:
            - ts-authkey
        volumes:
            - ts-bitwarden-state:/var/lib/tailscale:Z
            - ./bitwarden.json:/config/bitwarden.json:Z,ro
        devices:
            - /dev/net/tun:/dev/net/tun
        cap_add:
            - net_admin
        restart: unless-stopped
    bitwarden:
        image: ghcr.io/bitwarden/self-host:beta
        container_name: bitwarden
        network_mode: service:ts-bitwarden
        depends_on:
            - ts-bitwarden
        environment:
            BW_DB_PROVIDER: sqlite
            BW_DOMAIN_FILE: /run/secrets/bw-domain
            BW_INSTALLATION_ID_FILE: /run/secrets/bw-installation-id
            BW_INSTALLATION_KEY_FILE: /run/secrets/bw-installation-key
            adminSettings__admins_FILE: /run/secrets/bw-admins
        secrets:
            - bw-domain
            - bw-installation-id
            - bw-installation-key
            - bw-admins
        volumes:
            - bitwarden-data:/etc/bitwarden:Z
        restart: unless-stopped

secrets:
    ts-authkey:
        external: true
    bw-domain:
        external: true
    bw-installation-id:
        external: true
    bw-installation-key:
        external: true
    bw-admins:
        external: true

volumes:
    ts-bitwarden-state:
        name: ts-bitwarden-state
    bitwarden-data:
        name: bitwarden-data
