---
- name: Ensure system is up-to-date
  ansible.builtin.dnf:
      name: "*"
      state: latest
      update_cache: true

# - name: Ensure tailscale repository is present
# ansible.builtin.yum_repository:
# name: tailscale
# description: Tailscale stable
# baseurl: https://pkgs.tailscale.com/stable/fedora/$basearch
# repo_gpgcheck: true
# gpgcheck: true
# gpgkey: https://pkgs.tailscale.com/stable/fedora/repo.gpg

- name: Ensure essential packages are installed
  ansible.builtin.dnf:
      name:
          - firewalld
          - tailscale
          - cifs-utils
      state: latest

- name: Ensure essential services are enabled and started
  ansible.builtin.systemd_service:
      name: "{{ item }}"
      state: started
      enabled: true
  loop:
      - firewalld
      - tailscaled

- name: Ensure essential users are present
  ansible.builtin.user:
      name: "{{ item.name }}"
      groups: "{{ item.groups }}"
      state: present
  loop:
      - name: ansible
        groups: wheel
      - name: devops
        groups: wheel

- name: Ensure passwordless sudo for wheel group
  ansible.builtin.copy:
      src: wheel
      dest: /etc/sudoers.d/wheel
      owner: root
      group: root
      mode: 0640
      validate: "visudo -cf %s"
