---
- name: Homelab services deployment
  hosts: cloudlab
  become: true
  vars_files:
      - vault.yml
  roles:
      - common
      - pocket-id
      - gitea
      - bitwarden
      - searxng
      - memos
      - jellyfin
      - immich
      - glance
      - dumbpad
      - dumbdo
      - dumbkan
      - dumbbudget
      - dumbassets
      # - tsidp
