---
- name: Cloudlab general setup
  hosts: cloudlab
  become: true
  gather_facts: false
  # strategy: free
  vars_files:
      - vault.yml
  roles:
      - common

- name: Cloudlab services deployment
  hosts: cloudlab
  become: true
  gather_facts: false
  # strategy: free
  vars_files:
      - vault.yml
  roles:
      - pocket-id
      - stalwart
      - gitea
      - bitwarden
      - searxng
      - memos
      - jellyfin
      - immich
      - glance
      - dumbpad
      - dumbdo
      - dumbkan
      - dumbbudget
      - dumbassets
      # - tsidp
