---
- name: Homelab services deployment
  hosts: localhost
  become: true
  vars_files:
      - vault.yml
  roles:
      - general
      # - podman
      - pocket-id
      - gitea
      - bitwarden
      - searxng
      - memos
      - jellyfin
      - glance
      - dumbpad
      - dumbdo
      - dumbkan
      - dumbbudget
      - dumbassets
      # - tsidp
