---
- name: Server setup
  hosts: all
  become: true
  gather_facts: false
  vars_files:
      - vault.yml
  roles:
      - common
      - stalwart
      - pocket-id
      # - tsidp
      - bitwarden
      - immich
      - memos
      - gitea
      - dumbassets
      - dumbbudget
      - dumbdo
      - dumbkan
      - dumbpad
      - searxng
      - jellyfin
      - glance
