services:
    ts-memos:
        image: tailscale/tailscale:latest
        container_name: ts-memos
        hostname: memos
        environment:
            - TS_AUTHKEY=$TS_AUTHKEY
            - TS_STATE_DIR=/var/lib/tailscale
            - TS_USERSPACE=false
            - TS_SERVE_CONFIG=/config/serve-config.json
        volumes:
            - $PWD/data/ts-memos/state:/var/lib/tailscale
            - $PWD/data/ts-memos/config:/config
        devices:
            - /dev/net/tun:/dev/net/tun
        cap_add:
            - net_admin
        restart: unless-stopped
    memos:
        image: neosmemo/memos:stable
        container_name: memos
        network_mode: service:ts-memos
        depends_on:
            - ts-memos
        volumes:
            - "$PWD/data/memos:/var/opt/memos"
        restart: unless-stopped
