services:
    cloudflared:
        image: docker.io/cloudflare/cloudflared:latest
        container_name: cloudflared
        networks:
            - traefik
        environment:
            TUNNEL_TOKEN_FILE: /run/secrets/cf-tunnel-token
        secrets:
            - cf-tunnel-token
        command: tunnel run
        restart: unless-stopped

    traefik:
        image: docker.io/traefik:v3
        container_name: traefik
        networks:
            - traefik
        environment:
            CF_DNS_API_TOKEN_FILE: /run/secrets/cf-dns-api-token
        secrets:
            - cf-dns-api-token
        volumes:
            - ./traefik.yaml:/etc/traefik/traefik.yml:Z,ro
            - traefik-certs:/letsencrypt:z
            - /etc/localtime:/etc/localtime:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
        ports:
            - "80:80"
            - "443:443"
        labels:
            - "traefik.enable=false"
        restart: unless-stopped

    traefik-certs-dumper:
        image: ghcr.io/kereis/traefik-certs-dumper:latest
        container_name: traefik-certs-dumper
        depends_on:
            - traefik
        volumes:
            - traefik-certs:/traefik:z,ro
            - traefik-certs-dumper:/output:z
            - /etc/localtime:/etc/localtime:ro
        restart: unless-stopped

networks:
    traefik:
        name: traefik

secrets:
    cf-tunnel-token:
        external: true
    cf-dns-api-token:
        external: true

volumes:
    traefik-certs:
        name: traefik-certs
    traefik-certs-dumper:
        name: traefik-certs-dumper
