- name: RSS
  center-horizontally: true
  columns:
      - size: full
        widgets:
            - type: rss
              limit: 100
              collapse-after: 10
              cache: 12h
              feeds:
                  - url: https://selfh.st/rss/
                    title: selfh.st
                  - url: https://ciechanow.ski/atom.xml
                  - url: https://www.joshwcomeau.com/rss.xml
                    title: Josh Comeau
                  - url: https://samwho.dev/rss.xml
                  - url: https://ishadeed.com/feed.xml
                    title: Ahmad Shadeed
                  - url: https://blog.tangled.sh/blog/feed.xml
                    title: tangled engineering
                  - url: https://console.dev/rss.xml
                    title: Console.dev Devtools Newsletter - Everything Feed
                  - url: https://terminaltrove.com/totw.xml
                    title: Terminal Trove Tool of the Week
                  - url: https://blog.boot.dev/index.xml
                    title: Boot.dev Blog
                  - url: https://charm.sh/blog/rss.xml
                    title: The Charm Blog
                  - url: https://xcp-ng.org/blog/feed/
                    title: XCP-ng Blog
                  - url: http://www.bleepingcomputer.com/feed/
                    title: BleepingComputer
                  - url: https://blog.torproject.org/blog/feed
                    title: Tor Project blog
                  - url: https://www.phoronix.com/rss.php
                    title: Phoronix
                  - url: https://download.mikrotik.com/routeros/latest-stable-and-long-term.rss
                    title: MikroTik RouterOS Stable and Long-Term releases
                  - url: http://krebsonsecurity.com/feed/
                    title: Krebs on Security
                  - url: https://tailscale.com/blog/index.xml
                    title: Blog on Tailscale
                  - url: http://news.ycombinator.com/rss
                    title: Hacker News
                  - url: https://mullvad.net/en/blog/feed/atom/
                    title: The Mullvad Blog
                  - url: https://www.nobsbitcoin.com/rss/
                    title: No Bullshit Bitcoin
                  - url: https://fedoramagazine.org/feed/
                    title: Fedora Magazine
                  - url: http://www.hackaday.com/rss.xml
                    title: Blog – Hackaday
                  - url: https://www.theverge.com/rss/partner/subscriber-only-full-feed/rss.xml
                    title: The Verge - Full RSS for subscribers | The Verge
                  - url: https://planet.gnome.org/rss20.xml
                    title: Planet GNOME
                  - url: https://github.blog/feed/
                    title: The GitHub Blog
                  - url: https://kite.kagi.com/world.xml
                    title: Kite News - World
