services:
    ts-glance:
        image: docker.io/tailscale/tailscale:latest
        container_name: ts-glance
        hostname: glance
        environment:
            - TS_AUTHKEY=$TS_AUTHKEY
            - TS_STATE_DIR=/var/lib/tailscale
            - TS_USERSPACE=false
            - TS_SERVE_CONFIG=/config/serve-config.json
        volumes:
            - ts-glance-state:/var/lib/tailscale
            - ./serve-config.json:/config/serve-config.json
        devices:
            - /dev/net/tun:/dev/net/tun
        cap_add:
            - net_admin
        restart: unless-stopped

    glance:
        image: docker.io/glanceapp/glance:latest
        container_name: glance
        network_mode: service:ts-glance
        depends_on:
            - ts-glance
        env_file:
            - .env
        volumes:
            - ./config:/app/config
            - ./assets:/app/assets
            - /var/run/docker.sock:/var/run/docker.sock:ro
        restart: unless-stopped

volumes:
    ts-glance-state:
        name: ts-glance-state
