services:
    ts-glance:
        image: docker.io/tailscale/tailscale:latest
        container_name: ts-glance
        hostname: glance
        environment:
            - TS_AUTHKEY=$TS_AUTHKEY
            - TS_STATE_DIR=/var/lib/tailscale
            - TS_USERSPACE=false
            - TS_SERVE_CONFIG=/config/serve-config.json
        volumes:
            - ./data/ts-glance/state:/var/lib/tailscale
            - ./data/ts-glance/config:/config
        devices:
            - /dev/net/tun:/dev/net/tun
        cap_add:
            - net_admin
        restart: unless-stopped
    glance:
        image: docker.io/glanceapp/glance:latest
        container_name: glance
        network_mode: service:ts-glance
        depends_on:
            - ts-glance
        env_file: .env
        volumes:
            - ./data/glance/config:/app/config
            - ./data/glance/assets:/app/assets
            - /var/run/docker.sock:/var/run/docker.sock:ro
        restart: unless-stopped
